#!/bin/bash
#
# Скрипт исправляет ошибку долгой загрузки системы(timeout) после обновления Grub2, при установленном Zram.
#
# Отключаем Зрам
echo "Остановка Zram"
systemctl stop zram.service
#
echo "Обновление grub и initrd"
update-grub2 
dracut -f /boot/initrd-$(uname -r).img
#
urpmi --auto-update
#
echo "Запуск Zram"
systemctl start zram.service
#
echo "Готово! Конец операции!"
exit
